name: retail_dbt_project
version: 1.0
config-version: 2

profile: retail_dbt_project

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  retail_dbt_project:
    +catalog: workspace

    silver:
      +schema: silver

    gold:
      +schema: gold

    platinum:
      +schema: platinum

seeds:
  retail_dbt_project:
    +catalog: workspace
    +schema: dev

vars:
  batch_id: "BATCH_001"
  pipeline_name: "movie_pipeline"
  pipeline_run_id: "RUN_001"
